#!/bin/sh /etc/rc.common

START=95
STOP=10

USE_PROCD=1
PROG=/usr/bin/ESurfingClient
CONF=/etc/config/esurfingclient

validate_section() {
	uci_validate_section esurfingclient esurfingclient "${1}" \
		'enabled:bool:0' \
		'username:string' \
		'password:string' \
		'channel:string' \
    'debug:bool:0' \
    'smallDevice:bool:1'
}

start_service() {
	local enabled username password channel debug smallDevice
	
	validate_section main || {
		echo "validation failed"
		return 1
	}
	
	[ "$enabled" = "1" ] || return 1
	
	[ -n "$username" ] || {
		echo "username not set"
		return 1
	}
	
	[ -n "$password" ] || {
		echo "password not set"
		return 1
	}

  [ -n "$channel" ] || {
		echo "channel not set"
		return 1
	}
	
	procd_open_instance
	procd_set_param command "$PROG"
	procd_append_param command -u "$username"
	procd_append_param command -p "$password"
  procd_append_param command -c"$channel"
	
	[ "$debug" = "1" ] && procd_append_param command -d

	[ "$smallDevice" = "1" ] && procd_append_param command -s
	
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "esurfingclient"
}